### ISSUE TITLE
Size mismatch

### ISSUE THREAD

**Issue by QuasiLegendre** [cabooster/SRDTrans#9]
```python
python test.py --datasets_folder noisy --denoise_model cad_03hz --GPU 0 --patch_x 128 --patch_t 128
Parameters -----> 
Namespace(GPU='0', denoise_model='cad_03hz', datasets_folder='noisy', patch_x=128, patch_t=128, overlap_factor=0.5, datasets_path='./datasets', pth_path='./pth', output_path='./results', test_datasize=1000000, scale_factor=1, patch_y=128, gap_t=64, gap_x=64, gap_y=64, ngpu=1, batch_size=1)
If there are multiple models, only the last one will be used for denoising.
Stacks to be processed -----> 
Total stack umber ----->  1
noise_0.3Hz_50mWpower_1000frames_-0.83dBSNR_1000x490x490.tif
/home/jialab/anaconda3/envs/SRDTrans/lib/python3.12/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1704987289929/work/aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Using 1 GPU(s) for testing -----> 
Traceback (most recent call last):
  File "/home/jialab/SRDTrans/test.py", line 244, in <module>
    test()
  File "/home/jialab/SRDTrans/test.py", line 139, in test
    denoise_generator.module.load_state_dict(torch.load(model_name))  # parallel
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jialab/anaconda3/envs/SRDTrans/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SRDTrans:
	Missing key(s) in state_dict: "encoders.3.conv_net.SingleConv1.Conv3d.weight", "encoders.3.conv_net.SingleConv1.Conv3d.bias", "encoders.3.conv_net.SingleConv2.Conv3d.weight", "encoders.3.conv_net.SingleConv2.Conv3d.bias", "encoders.3.down_sample.weight", "encoders.3.down_sample.bias", "decoders.3.conv_net.SingleConv1.Conv3d.weight", "decoders.3.conv_net.SingleConv1.Conv3d.bias", "decoders.3.conv_net.SingleConv2.Conv3d.weight", "decoders.3.conv_net.SingleConv2.Conv3d.bias", "decoders.3.up_sample.weight", "decoders.3.up_sample.bias". 
	size mismatch for encoders.0.conv_net.SingleConv1.Conv3d.weight: copying a param with shape torch.Size([8, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([4, 1, 3, 3, 3]).
	size mismatch for encoders.0.conv_net.SingleConv1.Conv3d.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([4]).
	size mismatch for encoders.0.conv_net.SingleConv2.Conv3d.weight: copying a param with shape torch.Size([16, 8, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([8, 4, 3, 3, 3]).
	size mismatch for encoders.0.conv_net.SingleConv2.Conv3d.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
	size mismatch for encoders.0.down_sample.weight: copying a param with shape torch.Size([16, 16, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([8, 8, 3, 3, 3]).
	size mismatch for encoders.0.down_sample.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
	size mismatch for encoders.1.conv_net.SingleConv1.Conv3d.weight: copying a param with shape torch.Size([16, 16, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([8, 8, 3, 3, 3]).
	size mismatch for encoders.1.conv_net.SingleConv1.Conv3d.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
	size mismatch for encoders.1.conv_net.SingleConv2.Conv3d.weight: copying a param with shape torch.Size([32, 16, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 8, 3, 3, 3]).
	size mismatch for encoders.1.conv_net.SingleConv2.Conv3d.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for encoders.1.down_sample.weight: copying a param with shape torch.Size([32, 32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3, 3]).
	size mismatch for encoders.1.down_sample.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for encoders.2.conv_net.SingleConv1.Conv3d.weight: copying a param with shape torch.Size([32, 32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 3, 3]).
	size mismatch for encoders.2.conv_net.SingleConv1.Conv3d.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for encoders.2.conv_net.SingleConv2.Conv3d.weight: copying a param with shape torch.Size([64, 32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 16, 3, 3, 3]).
	size mismatch for encoders.2.conv_net.SingleConv2.Conv3d.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for encoders.2.down_sample.weight: copying a param with shape torch.Size([64, 64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3, 3]).
	size mismatch for encoders.2.down_sample.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for decoders.2.conv_net.SingleConv1.Conv3d.weight: copying a param with shape torch.Size([1, 16, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([8, 16, 3, 3, 3]).
	size mismatch for decoders.2.conv_net.SingleConv1.Conv3d.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([8]).
	size mismatch for decoders.2.conv_net.SingleConv2.Conv3d.weight: copying a param with shape torch.Size([1, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([8, 8, 3, 3, 3]).
	size mismatch for decoders.2.conv_net.SingleConv2.Conv3d.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([8]).
	size mismatch for layers.0.timeTrans.position_encoding.position_embeddings: copying a param with shape torch.Size([1, 16, 128]) from checkpoint, the shape in current model is torch.Size([1, 8, 128]).
``` 
I only have one GPU, and found this size mismatch issue. I used Pretrained_0.3Hz_50mWpower_1000frames.pth as model and noise_0.3Hz_50mWpower_1000frames_-0.83dBSNR_1000x490x490.tif for test. I am using python==3.12, pytorch==2.2.

**Comment by QuasiLegendre** [comment]
I used Pretrained_0.3Hz_50mWpower_1000frames.pth as model and noise_0.3Hz_50mWpower_1000frames_-0.83dBSNR_1000x490x490.tif for test.

**Comment by josueortc** [comment]
I am having the same problem, problably is a config problem.

**Comment by Huxiaowan** [comment]
We apologize for the error in uploading the model with the parameter "f_maps=[16, 32, 64]", which led to size mismatch errors. We have now uploaded the correct model. You may proceed to download the model again and complete the testing process as usual. We appreciate your valuable feedback, which has helped us rectify the issue.
